/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDeParaRouteImport } from './routes/_authenticated/de-para'
import { Route as AuthenticatedDadosRouteImport } from './routes/_authenticated/dados'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeParaRoute = AuthenticatedDeParaRouteImport.update({
  id: '/de-para',
  path: '/de-para',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDadosRoute = AuthenticatedDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dados': typeof AuthenticatedDadosRoute
  '/de-para': typeof AuthenticatedDeParaRoute
  '/import': typeof AuthenticatedImportRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dados': typeof AuthenticatedDadosRoute
  '/de-para': typeof AuthenticatedDeParaRoute
  '/import': typeof AuthenticatedImportRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dados': typeof AuthenticatedDadosRoute
  '/_authenticated/de-para': typeof AuthenticatedDeParaRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dados'
    | '/de-para'
    | '/import'
    | '/produtos'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dados'
    | '/de-para'
    | '/import'
    | '/produtos'
    | '/settings'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dados'
    | '/_authenticated/de-para'
    | '/_authenticated/import'
    | '/_authenticated/produtos'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/de-para': {
      id: '/_authenticated/de-para'
      path: '/de-para'
      fullPath: '/de-para'
      preLoaderRoute: typeof AuthenticatedDeParaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dados': {
      id: '/_authenticated/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof AuthenticatedDadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDadosRoute: typeof AuthenticatedDadosRoute
  AuthenticatedDeParaRoute: typeof AuthenticatedDeParaRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDadosRoute: AuthenticatedDadosRoute,
  AuthenticatedDeParaRoute: AuthenticatedDeParaRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
